import test from 'node:test';import assert from 'node:assert/strict';
import { units,MAX_UNITS,digest,canonical,sumUnits } from '../../src/domain/primitives.ts';
import { parsePlan,commitment } from '../../src/domain/model.ts';
import { fixture,sealed,plan,delivery,admin,agent,NOW,project } from '../fixtures.ts';
for(const v of ['0','-1','1.5','1e6','01','+1',' 1',1,null,undefined,MAX_UNITS+1n])test(`amount rejects ${String(v)}`,()=>assert.throws(()=>units(v)));
test('amount exact above Number safe integer',()=>assert.equal(units('9007199254740993'),9007199254740993n));
test('sum overflow',()=>assert.throws(()=>sumUnits([MAX_UNITS.toString(),'1'])));
test('canonical stable regardless object order',()=>assert.equal(digest({b:2,a:1}),digest({a:1,b:2})));
test('canonical rejects undefined',()=>assert.throws(()=>canonical({a:undefined})));
test('canonical rejects float',()=>assert.throws(()=>canonical({a:1.1})));
test('correct plan preserves all criteria',()=>assert.equal(parsePlan(plan(),NOW).milestones.length,2));
test('budget must equal milestone amounts',()=>{const p=plan();p.totalUnits='1';assert.throws(()=>parsePlan(p,NOW),/exactly equal/);});
test('cycle or forward dependency rejected',()=>{const p=plan();p.milestones[0].dependsOn=['two'];assert.throws(()=>parsePlan(p,NOW),/earlier/);});
test('duplicate milestone rejected',()=>{const p=plan();p.milestones[1].id='one';assert.throws(()=>parsePlan(p,NOW),/Duplicate milestone/);});
test('duplicate criterion rejected',()=>{const p=plan();p.milestones[0].criteria.push(p.milestones[0].criteria[0]);assert.throws(()=>parsePlan(p,NOW),/Duplicate criterion/);});
test('deadline must be future',()=>{const p=plan();p.deadline=NOW;assert.throws(()=>parsePlan(p,NOW),/Deadline/);});
test('unknown plan field rejected',()=>assert.throws(()=>parsePlan({...plan(),approve:true},NOW),/Unknown fields/));
test('persist draft without embedded model',()=>{const f=fixture();assert.equal(f.w.state,'DRAFT');assert.equal(f.w.planHash,null);f.db.close();});
test('idempotent create produces one work',()=>{const f=fixture();const w=f.svc.save(agent,'demo',{plan:plan()},'save');assert.equal(w.id,f.w.id);assert.equal(f.db.list('work').length,1);f.db.close();});
test('idempotency rejects changed body',()=>{const f=fixture();const p=plan();p.title='changed';assert.throws(()=>f.svc.save(agent,'demo',{plan:p},'save'),/different input/);f.db.close();});
test('optimistic version conflict',()=>{const f=fixture();const p=plan();p.title='new';f.svc.save(agent,'demo',{workId:f.w.id,expectedVersion:1,plan:p},'update');assert.throws(()=>f.svc.save(agent,'demo',{workId:f.w.id,expectedVersion:1,plan:p},'update2'),/Reload/);f.db.close();});
test('agent cannot seal',()=>{const f=fixture();assert.throws(()=>f.svc.seal(agent,f.w.id,{expectedVersion:1},'x'),/Human/);f.db.close();});
test('sealed work cannot be rewritten',()=>{const f=sealed();assert.throws(()=>f.svc.save(agent,'demo',{workId:f.w.id,expectedVersion:f.w.version,plan:plan()},'x'),/cannot be rewritten/);f.db.close();});
test('agent cannot register payment destinations',()=>{const f=fixture();assert.throws(()=>f.svc.createProject(agent,{...project,id:'other'},'x'),/Human/);f.db.close();});
test('project visibility scoped',()=>{const f=fixture();f.svc.createProject(admin,{...project,id:'other'},'other');assert.equal(f.svc.projects(agent).length,1);assert.throws(()=>f.svc.project(agent,'other'),/outside/);f.db.close();});
test('commitment binds project parties',()=>{const f=sealed();assert.notEqual(commitment(f.w,project,f.svc.contractId),commitment(f.w,{...project,payee:'G'+'C'.repeat(55)},f.svc.contractId));f.db.close();});
test('commitment binds network contract configuration',()=>{const f=sealed();assert.notEqual(commitment(f.w,project,'A'),commitment(f.w,project,'B'));f.db.close();});
test('no delivery means not ready',()=>{const f=sealed();assert.equal(f.svc.readiness(agent,f.w.id,'one').readyForHumanReview,false);f.db.close();});
test('PASS yields human-review readiness, never acceptance',()=>{const f=sealed();f.svc.deliver(agent,f.w.id,delivery(),'d');const r=f.svc.readiness(agent,f.w.id,'one');assert.equal(r.readyForHumanReview,true);assert.equal(r.automaticallyAccepted,false);assert.equal(r.independentVerification,false);f.db.close();});
for(const status of ['FAIL','NOT_CHECKED'])test(`${status} blocks readiness and approve request`,()=>{const f=sealed();const d=f.svc.deliver(agent,f.w.id,delivery(status),'d');assert.equal(f.svc.readiness(agent,f.w.id,'one').readyForHumanReview,false);assert.throws(()=>f.svc.prepare(agent,f.w.id,{action:'approve',milestoneId:'one',evidenceHash:d.evidenceHash},'i'),/dedupe/);f.db.close();});
test('cannot assert trusted provenance from API payload',()=>{const f=sealed();assert.throws(()=>f.svc.deliver(agent,f.w.id,{...delivery(),provenance:'trusted_ci'},'d'),/Unknown fields/);f.db.close();});
test('trusted CI requirement fails closed without verifier integration',()=>{const f=fixture();const p=plan();p.milestones[0].criteria[0].evidence='trusted_ci';const w=f.svc.save(agent,'demo',{workId:f.w.id,expectedVersion:1,plan:p},'edit');f.svc.seal(admin,w.id,{expectedVersion:w.version},'s');f.svc.deliver(agent,w.id,delivery(),'d');assert.ok(f.svc.readiness(agent,w.id,'one').blockers.includes('dedupe:TRUSTED_CI_NOT_AVAILABLE'));f.db.close();});
test('all mandatory criteria require one result',()=>{const f=sealed();assert.throws(()=>f.svc.deliver(agent,f.w.id,{...delivery(),checks:[]},'d'),/exactly one/);f.db.close();});
test('unknown criterion rejected',()=>{const f=sealed();const d=delivery();d.checks[0].criterionId='foreign';assert.throws(()=>f.svc.deliver(agent,f.w.id,d,'d'),/Unknown/);f.db.close();});
test('artifact must use strong exact digest',()=>{const f=sealed();assert.throws(()=>f.svc.deliver(agent,f.w.id,{...delivery(),artifactHash:'main'},'d'),/SHA/);f.db.close();});
test('javascript evidence URL rejected',()=>{const f=sealed();assert.throws(()=>f.svc.deliver(agent,f.w.id,{...delivery(),reference:'javascript:alert(1)'},'d'),/HTTP/);f.db.close();});
test('new delivery changes evidence commitment',()=>{const f=sealed();const d1=f.svc.deliver(agent,f.w.id,delivery(),'d1');const d2=f.svc.deliver(agent,f.w.id,{...delivery(),artifactHash:'cd'.repeat(32)},'d2');assert.notEqual(d1.evidenceHash,d2.evidenceHash);f.db.close();});
test('failed update rolls back audit and work',()=>{const f=sealed();const before=f.db.list('work');assert.throws(()=>f.svc.save(agent,'demo',{workId:f.w.id,expectedVersion:2,plan:plan()},'bad'));assert.deepEqual(f.db.list('work'),before);f.db.close();});
test('progress does not become payment status',()=>{const f=sealed();f.svc.progress(agent,f.w.id,{milestoneId:'one',status:'READY_FOR_REVIEW',note:'done locally'},'p');assert.equal(f.svc.intents(agent,f.w.id).length,0);assert.equal(f.svc.readiness(agent,f.w.id,'one').readyForHumanReview,false);f.db.close();});

test('exact idempotent retry remains valid after deadline',()=>{const f=fixture();f.svc.now=()=>NOW+2000;const w=f.svc.save(agent,'demo',{plan:plan()},'save');assert.equal(w.id,f.w.id);f.db.close();});
