import test from 'node:test';import assert from 'node:assert/strict';import { application } from '../../src/server/app.ts';import { PaymentService } from '../../src/service/payment-service.ts';import { offlineChain } from '../../src/stellar/offline.ts';import { admin,agent,fixture,NOW,plan } from '../fixtures.ts';import type { AddressInfo } from 'node:net';import { request } from 'node:http';
async function server(){const f=fixture();const config={adminToken:'a'.repeat(64),agentToken:'b'.repeat(64),agentProjects:['demo'],db:':memory:',port:0,origin:'',mode:'local' as const,contractId:'UNCONFIGURED_TESTNET_CONTRACT',rpcUrl:'https://soroban-testnet.stellar.org'};const s=application(config,f.svc,new PaymentService(f.svc,offlineChain()));await new Promise<void>(resolve=>s.listen(0,'127.0.0.1',resolve));const port=(s.address() as AddressInfo).port;config.port=port;config.origin=`http://127.0.0.1:${port}`;return {...f,s,url:config.origin,close:async()=>{await new Promise<void>(resolve=>s.close(()=>resolve()));f.db.close();}};}
function headers(token='b'){return {Authorization:`Bearer ${token.repeat(64)}`,'Content-Type':'application/json','Idempotency-Key':'http'};}
test('health honestly says no simulated payments',async()=>{const f=await server();try{const d=await (await fetch(f.url+'/healthz')).json();assert.equal(d.paymentsSimulated,false);}finally{await f.close();}});
test('API requires authentication',async()=>{const f=await server();try{assert.equal((await fetch(f.url+'/api/projects')).status,401);}finally{await f.close();}});
test('host defense rejects DNS rebinding',async()=>{const f=await server();try{const code=await new Promise<number|undefined>((resolve,reject)=>{const req=request(f.url+'/api/projects',{headers:{...headers(),Host:'evil.example'}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);req.end();});assert.equal(code,403);}finally{await f.close();}});
test('cross-origin even with token is rejected',async()=>{const f=await server();try{assert.equal((await fetch(f.url+'/api/projects',{headers:{...headers(),Origin:'https://evil.example'}})).status,403);}finally{await f.close();}});
test('agent can create structured draft over actual HTTP',async()=>{const f=await server();try{const r=await fetch(f.url+'/api/projects/demo/works',{method:'POST',headers:headers(),body:JSON.stringify({plan:plan()})});assert.equal(r.status,200);assert.equal((await r.json()).state,'DRAFT');}finally{await f.close();}});
test('sealing over agent HTTP rejected',async()=>{const f=await server();try{const r=await fetch(f.url+`/api/works/${f.w.id}/seal`,{method:'POST',headers:headers(),body:JSON.stringify({expectedVersion:1})});assert.equal(r.status,403);}finally{await f.close();}});
test('missing idempotency key rejected',async()=>{const f=await server();try{const r=await fetch(f.url+'/api/projects/demo/works',{method:'POST',headers:{Authorization:'Bearer '+'b'.repeat(64),'Content-Type':'application/json'},body:JSON.stringify({plan:plan()})});assert.equal(r.status,400);}finally{await f.close();}});
test('wrong content type rejected',async()=>{const f=await server();try{const r=await fetch(f.url+'/api/projects/demo/works',{method:'POST',headers:{...headers(),'Content-Type':'text/plain'},body:JSON.stringify({plan:plan()})});assert.equal(r.status,415);}finally{await f.close();}});
test('payload limit',async()=>{const f=await server();try{const r=await fetch(f.url+'/api/projects/demo/works',{method:'POST',headers:headers(),body:JSON.stringify({junk:'x'.repeat(260000)})});assert.equal(r.status,413);}finally{await f.close();}});
test('public UI has restrictive CSP and no embedded tokens',async()=>{const f=await server();try{const r=await fetch(f.url);const s=await r.text();assert.match(r.headers.get('content-security-policy')??'',/frame-ancestors 'none'/);assert.equal(s.includes('a'.repeat(64)),false);assert.match(s,/sin fondos reales/);}finally{await f.close();}});

test('agent progress is retrievable in project context',async()=>{const f=await server();try{let r=await fetch(f.url+`/api/works/${f.w.id}/progress`,{method:'POST',headers:headers(),body:JSON.stringify({milestoneId:f.w.plan.milestones[0].id,status:'IN_PROGRESS',note:'Preparing fixture'})});assert.equal(r.status,200);r=await fetch(f.url+`/api/works/${f.w.id}`,{headers:headers()});const context=await r.json();assert.equal(context.progress.length,1);assert.equal(context.progress[0].workId,f.w.id);assert.equal(context.progress[0].status,'IN_PROGRESS');}finally{await f.close();}});
test('recovery route is admin-only for a stale PREPARING lease',async()=>{const f=await server();try{f.svc.seal(admin,f.w.id,{expectedVersion:f.w.version},'http-recover-seal');const requested=f.svc.prepare(agent,f.w.id,{action:'create'},'http-recover');const i=f.svc.intent(admin,requested.id);f.db.acquire(i.source,i.id);f.db.put('intent',i.id,'demo',{...i,status:'PREPARING',preparingAt:NOW-301,buildAttempt:'http-attempt'});let r=await fetch(f.url+`/api/intents/${i.id}/recover`,{method:'POST',headers:headers(),body:'{}'});assert.equal(r.status,403);r=await fetch(f.url+`/api/intents/${i.id}/recover`,{method:'POST',headers:headers('a'),body:'{}'});const body=await r.json();assert.equal(r.status,200,JSON.stringify(body));assert.equal(body.status,'BUILD_FAILED');assert.equal('buildAttempt'in body,false);}finally{await f.close();}});
