import test from 'node:test';import assert from 'node:assert/strict';import { mkdtempSync,rmSync } from 'node:fs';import { tmpdir } from 'node:os';import { join } from 'node:path';
import { payments,fixture,FakeChain,admin,agent,NOW,delivery } from '../fixtures.ts';
import { Database } from '../../src/storage/database.ts';import { WorkService } from '../../src/service/work-service.ts';import { PaymentService } from '../../src/service/payment-service.ts';import { offlineChain } from '../../src/stellar/offline.ts';import { contractArguments } from '../../src/stellar/adapter.ts';
function intent(f:ReturnType<typeof payments>,key='i'){return f.svc.prepare(agent,f.w.id,{action:'create'},key);}
test('agent can prepare but cannot build or sign',async()=>{const f=payments();const i=intent(f);assert.equal(i.status,'REQUESTED');assert.equal(i.txHash,null);await assert.rejects(()=>f.pay.build(agent,i.id),/Human/);assert.equal(f.chain.builds,0);f.db.close();});
test('intent idempotency',()=>{const f=payments();assert.equal(intent(f).id,intent(f).id);f.db.close();});
test('destinations cannot be injected',()=>{const f=payments();assert.throws(()=>f.svc.prepare(agent,f.w.id,{action:'create',source:'attacker'},'i'),/Unknown fields/);f.db.close();});
test('successful build locks wallet and returns unsigned envelope',async()=>{const f=payments();const i=intent(f);const b=await f.pay.build(admin,i.id);assert.equal(b.unsignedXdr,'FAKE_UNSIGNED');assert.equal(b.status,'READY');assert.equal((await f.pay.build(admin,i.id)).txHash,b.txHash);assert.equal(f.chain.builds,1);const j=intent(f,'j');await assert.rejects(()=>f.pay.build(admin,j.id),/unresolved/);f.db.close();});
test('bad signature never broadcasts',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);await assert.rejects(()=>f.pay.submit(admin,i.id,'bad'),/Invalid/);assert.equal(f.chain.sends,0);f.db.close();});
test('agent cannot submit even if envelope supplied',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);await assert.rejects(()=>f.pay.submit(agent,i.id,'FAKE_SIGNED'),/Human/);assert.equal(f.chain.sends,0);f.db.close();});
test('submitted is NOT successful',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);const s=await f.pay.submit(admin,i.id,'FAKE_SIGNED');assert.equal(s.status,'SUBMITTED');assert.equal(s.ledger,null);f.db.close();});
test('network timeout stays UNKNOWN and retry never creates second payment',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);f.chain.timeout=true;assert.equal((await f.pay.submit(admin,i.id,'FAKE_SIGNED')).status,'UNKNOWN');await f.pay.submit(admin,i.id,'FAKE_SIGNED');await f.pay.reconcile(agent,i.id);assert.equal(f.chain.sends,1);assert.equal(f.chain.builds,1);f.db.close();});
test('confirmed success releases source lock',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);await f.pay.submit(admin,i.id,'FAKE_SIGNED');f.chain.result={status:'SUCCESS',ledger:55};assert.equal((await f.pay.reconcile(agent,i.id)).ledger,55);assert.equal((await f.pay.build(admin,intent(f,'j').id)).status,'READY');f.db.close();});
test('terminal success cannot regress',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);await f.pay.submit(admin,i.id,'FAKE_SIGNED');f.chain.result={status:'SUCCESS',ledger:55};await f.pay.reconcile(agent,i.id);f.chain.result={status:'UNKNOWN'};assert.equal((await f.pay.reconcile(agent,i.id)).status,'SUCCESS');f.db.close();});
test('confirmed failure is explicit',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);await f.pay.submit(admin,i.id,'FAKE_SIGNED');f.chain.result={status:'FAILED',ledger:12};assert.equal((await f.pay.reconcile(admin,i.id)).status,'FAILED');f.db.close();});
test('expired envelope cannot be signed',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);f.svc.now=()=>NOW+200;await assert.rejects(()=>f.pay.submit(admin,i.id,'FAKE_SIGNED'),/expired/);assert.equal(f.chain.sends,0);f.db.close();});
test('public intent never exposes signed envelope',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);await f.pay.submit(admin,i.id,'FAKE_SIGNED');const p=f.svc.publicIntent(f.svc.intent(agent,i.id));assert.equal('signedXdr'in p,false);assert.equal('unsignedXdr'in p,false);f.db.close();});
test('offline mode never simulates payments',async()=>{const f=payments();const pay=new PaymentService(f.svc,offlineChain());const i=intent(f);await assert.rejects(()=>pay.build(admin,i.id),/NO simulated/);assert.equal(f.svc.intent(agent,i.id).status,'BUILD_FAILED');f.db.close();});
test('durable unknown submission survives process restart',async()=>{const dir=mkdtempSync(join(tmpdir(),'hito-'));try{const path=join(dir,'db');let f=fixture(path);f.svc.seal(admin,f.w.id,{expectedVersion:1},'s');const chain=new FakeChain();chain.timeout=true;let pay=new PaymentService(f.svc,chain);const i=f.svc.prepare(agent,f.w.id,{action:'create'},'i');await pay.build(admin,i.id);await pay.submit(admin,i.id,'FAKE_SIGNED');f.db.close();const db=new Database(path);const svc=new WorkService(db,'UNCONFIGURED_TESTNET_CONTRACT',()=>NOW);pay=new PaymentService(svc,chain);assert.equal(svc.intent(agent,i.id).status,'UNKNOWN');chain.result={status:'SUCCESS',ledger:99};assert.equal((await pay.reconcile(agent,i.id)).status,'SUCCESS');assert.equal(chain.sends,1);db.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('contract arguments include dependency masks and integer strings',()=>{const f=payments();const i=intent(f);const a=contractArguments(f.svc.intent(admin,i.id),f.w,f.svc.project(admin,'demo'));assert.equal(a.method,'create');assert.deepEqual(a.args[5].value,[0,1]);assert.deepEqual(a.args[4].value,['40000000','60000000']);f.db.close();});
test('wrong delivery hash cannot prepare acceptance',()=>{const f=payments();f.svc.deliver(agent,f.w.id,delivery(),'d');assert.throws(()=>f.svc.prepare(agent,f.w.id,{action:'approve',milestoneId:'one',evidenceHash:'00'.repeat(32)},'i'),/not found/);f.db.close();});

for (const [rpc,expected] of [['PENDING','SUBMITTED'],['DUPLICATE','SUBMITTED'],['ERROR','UNKNOWN'],['TRY_AGAIN_LATER','UNKNOWN']]) {
  test(`RPC ${rpc} is not a final ledger result`,async()=>{const {submissionOutcome}=await import('../../src/stellar/adapter.ts');assert.equal(submissionOutcome(rpc).status,expected);});
}
