import test from 'node:test';import assert from 'node:assert/strict';import { mkdtempSync,rmSync } from 'node:fs';import { tmpdir } from 'node:os';import { join } from 'node:path';
import { payments,fixture,FakeChain,admin,agent,NOW,delivery } from '../fixtures.ts';
import { Database } from '../../src/storage/database.ts';import { WorkService } from '../../src/service/work-service.ts';import { PaymentService } from '../../src/service/payment-service.ts';import { offlineChain } from '../../src/stellar/offline.ts';import { contractArguments } from '../../src/stellar/adapter.ts';
import type { Prepared,ChainResult } from '../../src/stellar/port.ts';
function intent(f:ReturnType<typeof payments>,key='i'){return f.svc.prepare(agent,f.w.id,{action:'create'},key);}
test('agent can prepare but cannot build or sign',async()=>{const f=payments();const i=intent(f);assert.equal(i.status,'REQUESTED');assert.equal(i.txHash,null);await assert.rejects(()=>f.pay.build(agent,i.id),/Human/);assert.equal(f.chain.builds,0);f.db.close();});
test('intent idempotency',()=>{const f=payments();assert.equal(intent(f).id,intent(f).id);f.db.close();});
test('destinations cannot be injected',()=>{const f=payments();assert.throws(()=>f.svc.prepare(agent,f.w.id,{action:'create',source:'attacker'},'i'),/Unknown fields/);f.db.close();});
test('successful build locks wallet and returns unsigned envelope',async()=>{const f=payments();const i=intent(f);const b=await f.pay.build(admin,i.id);assert.equal(b.unsignedXdr,'FAKE_UNSIGNED');assert.equal(b.status,'READY');assert.equal((await f.pay.build(admin,i.id)).txHash,b.txHash);assert.equal(f.chain.builds,1);const j=intent(f,'j');await assert.rejects(()=>f.pay.build(admin,j.id),/unresolved/);f.db.close();});
test('bad signature never broadcasts',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);await assert.rejects(()=>f.pay.submit(admin,i.id,'bad'),/Invalid/);assert.equal(f.chain.sends,0);f.db.close();});
test('agent cannot submit even if envelope supplied',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);await assert.rejects(()=>f.pay.submit(agent,i.id,'FAKE_SIGNED'),/Human/);assert.equal(f.chain.sends,0);f.db.close();});
test('submitted is NOT successful',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);const s=await f.pay.submit(admin,i.id,'FAKE_SIGNED');assert.equal(s.status,'SUBMITTED');assert.equal(s.ledger,null);f.db.close();});
test('network timeout stays UNKNOWN and retry never creates second payment',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);f.chain.timeout=true;assert.equal((await f.pay.submit(admin,i.id,'FAKE_SIGNED')).status,'UNKNOWN');await f.pay.submit(admin,i.id,'FAKE_SIGNED');await f.pay.reconcile(agent,i.id);assert.equal(f.chain.sends,1);assert.equal(f.chain.builds,1);f.db.close();});
test('confirmed success releases source lock',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);await f.pay.submit(admin,i.id,'FAKE_SIGNED');f.chain.result={status:'SUCCESS',ledger:55};assert.equal((await f.pay.reconcile(agent,i.id)).ledger,55);assert.equal((await f.pay.build(admin,intent(f,'j').id)).status,'READY');f.db.close();});
test('terminal success cannot regress',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);await f.pay.submit(admin,i.id,'FAKE_SIGNED');f.chain.result={status:'SUCCESS',ledger:55};await f.pay.reconcile(agent,i.id);f.chain.result={status:'UNKNOWN'};assert.equal((await f.pay.reconcile(agent,i.id)).status,'SUCCESS');f.db.close();});
test('confirmed failure is explicit',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);await f.pay.submit(admin,i.id,'FAKE_SIGNED');f.chain.result={status:'FAILED',ledger:12};assert.equal((await f.pay.reconcile(admin,i.id)).status,'FAILED');f.db.close();});
test('expired envelope cannot be signed',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);f.svc.now=()=>NOW+200;await assert.rejects(()=>f.pay.submit(admin,i.id,'FAKE_SIGNED'),/expired/);assert.equal(f.chain.sends,0);f.db.close();});
test('expired READY remains locked when lookup is UNKNOWN',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);f.svc.now=()=>NOW+200;await assert.rejects(()=>f.pay.recover(admin,i.id),/does not prove/);assert.equal(f.svc.intent(admin,i.id).status,'READY');await assert.rejects(()=>f.pay.build(admin,intent(f,'next').id),/unresolved/);f.db.close();});
test('expired READY unlocks only after a confirmed terminal lookup',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);f.svc.now=()=>NOW+200;f.chain.result={status:'FAILED',ledger:12};assert.equal((await f.pay.recover(admin,i.id)).status,'FAILED');assert.equal((await f.pay.build(admin,intent(f,'next').id)).status,'READY');f.db.close();});
test('active PREPARING lease cannot be recovered',async()=>{const f=payments();let finish:(p:Prepared)=>void=()=>{};f.chain.prepare=async()=>new Promise(resolve=>{finish=resolve;});const i=intent(f);const pending=f.pay.build(admin,i.id);await assert.rejects(()=>f.pay.recover(admin,i.id),/still active/);finish({unsignedXdr:'FAKE_UNSIGNED',txHash:'a'.repeat(64),expiresAt:NOW+180});assert.equal((await pending).status,'READY');f.db.close();});
test('stale PREPARING recovery is admin-only, fences a late builder and releases the source',async()=>{const f=payments();let now=NOW;f.svc.now=()=>now;let finish:(p:Prepared)=>void=()=>{};f.chain.prepare=async()=>new Promise(resolve=>{finish=resolve;});const i=intent(f);const pending=f.pay.build(admin,i.id);now+=301;await assert.rejects(()=>f.pay.recover(agent,i.id),/Human/);assert.equal((await f.pay.recover(admin,i.id)).status,'BUILD_FAILED');finish({unsignedXdr:'FAKE_UNSIGNED',txHash:'b'.repeat(64),expiresAt:now+180});await assert.rejects(()=>pending,/lease no longer belongs/);assert.equal(f.svc.intent(admin,i.id).status,'BUILD_FAILED');f.chain.prepare=async()=>({unsignedXdr:'FAKE_UNSIGNED_2',txHash:'c'.repeat(64),expiresAt:now+180});assert.equal((await f.pay.build(admin,intent(f,'next').id)).status,'READY');f.db.close();});
test('legacy PREPARING without a lease timestamp remains conservatively locked',async()=>{const f=payments();const i=f.svc.intent(admin,intent(f).id);f.db.acquire(i.source,i.id);f.db.put('intent',i.id,'demo',{...i,status:'PREPARING'});await assert.rejects(()=>f.pay.recover(admin,i.id),/no auditable lease timestamp/);assert.equal(f.svc.intent(admin,i.id).status,'PREPARING');f.db.close();});
test('public intent never exposes envelopes or internal build fencing',async()=>{const f=payments();const i=intent(f);await f.pay.build(admin,i.id);await f.pay.submit(admin,i.id,'FAKE_SIGNED');const p=f.svc.publicIntent(f.svc.intent(agent,i.id));assert.equal('signedXdr'in p,false);assert.equal('unsignedXdr'in p,false);assert.equal('preparingAt'in p,false);assert.equal('buildAttempt'in p,false);f.db.close();});
test('offline mode never simulates payments',async()=>{const f=payments();const pay=new PaymentService(f.svc,offlineChain());const i=intent(f);await assert.rejects(()=>pay.build(admin,i.id),/NO simulated/);assert.equal(f.svc.intent(agent,i.id).status,'BUILD_FAILED');f.db.close();});
test('durable unknown submission survives process restart',async()=>{const dir=mkdtempSync(join(tmpdir(),'hito-'));try{const path=join(dir,'db');let f=fixture(path);f.svc.seal(admin,f.w.id,{expectedVersion:1},'s');const chain=new FakeChain();chain.timeout=true;let pay=new PaymentService(f.svc,chain);const i=f.svc.prepare(agent,f.w.id,{action:'create'},'i');await pay.build(admin,i.id);await pay.submit(admin,i.id,'FAKE_SIGNED');f.db.close();const db=new Database(path);const svc=new WorkService(db,'UNCONFIGURED_TESTNET_CONTRACT',()=>NOW);pay=new PaymentService(svc,chain);assert.equal(svc.intent(agent,i.id).status,'UNKNOWN');chain.result={status:'SUCCESS',ledger:99};assert.equal((await pay.reconcile(agent,i.id)).status,'SUCCESS');assert.equal(chain.sends,1);db.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('crash checkpoint before broadcast remains UNKNOWN and does not rebroadcast',async()=>{const dir=mkdtempSync(join(tmpdir(),'hito-before-send-'));try{const path=join(dir,'db');let f=fixture(path);f.svc.seal(admin,f.w.id,{expectedVersion:1},'s');const chain=new FakeChain();let pay=new PaymentService(f.svc,chain);const requested=f.svc.prepare(agent,f.w.id,{action:'create'},'i');await pay.build(admin,requested.id);const built=f.svc.intent(admin,requested.id);f.db.put('intent',built.id,'demo',{...built,status:'SUBMITTING',signedXdr:'FAKE_SIGNED'});f.db.close();const db=new Database(path);const svc=new WorkService(db,'UNCONFIGURED_TESTNET_CONTRACT',()=>NOW);pay=new PaymentService(svc,chain);assert.equal((await pay.reconcile(admin,built.id)).status,'UNKNOWN');assert.equal(chain.sends,0);await assert.rejects(()=>pay.build(admin,svc.prepare(agent,f.w.id,{action:'create'},'next').id),/unresolved/);db.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('reconcile racing a broadcast cannot regress confirmed success',async()=>{const f=payments();let finish:(r:ChainResult)=>void=()=>{};f.chain.broadcast=async()=>{f.chain.sends++;return new Promise(resolve=>{finish=resolve;});};const i=intent(f);await f.pay.build(admin,i.id);const submitting=f.pay.submit(admin,i.id,'FAKE_SIGNED');await new Promise(resolve=>setImmediate(resolve));assert.equal(f.svc.intent(admin,i.id).status,'SUBMITTING');f.chain.result={status:'SUCCESS',ledger:77};assert.equal((await f.pay.reconcile(admin,i.id)).status,'SUCCESS');finish({status:'SUBMITTED'});assert.equal((await submitting).status,'SUCCESS');assert.equal(f.chain.sends,1);f.db.close();});
test('contract arguments include dependency masks and integer strings',()=>{const f=payments();const i=intent(f);const a=contractArguments(f.svc.intent(admin,i.id),f.w,f.svc.project(admin,'demo'));assert.equal(a.method,'create');assert.deepEqual(a.args[5].value,[0,1]);assert.deepEqual(a.args[4].value,['40000000','60000000']);f.db.close();});
test('wrong delivery hash cannot prepare acceptance',()=>{const f=payments();f.svc.deliver(agent,f.w.id,delivery(),'d');assert.throws(()=>f.svc.prepare(agent,f.w.id,{action:'approve',milestoneId:'one',evidenceHash:'00'.repeat(32)},'i'),/not found/);f.db.close();});

for (const [rpc,expected] of [['PENDING','SUBMITTED'],['DUPLICATE','SUBMITTED'],['ERROR','UNKNOWN'],['TRY_AGAIN_LATER','UNKNOWN']]) {
  test(`RPC ${rpc} is not a final ledger result`,async()=>{const {submissionOutcome}=await import('../../src/stellar/adapter.ts');assert.equal(submissionOutcome(rpc).status,expected);});
}
